### ISSUE TITLE
Prevent default seek behavior

### ISSUE THREAD

**Issue by Foreweed** [bbc/peaks.js#162]
Hello,

First I want to thank you for the great job you did with this project.
I have a question for you: I want to prevent the user from seeking overview or zoomview on selected segments. I've seen your events user_seek.overview and user_seek.zoomview, and I wonder: are those events called before or after actually moving the cursor to the clicked position? And if it's before, is there a way to prevent the default behavior (which consists in moving the cursor to the clicked position)?

**Comment by chrisn** [comment]
These events are emitted before the cursor is moved (and the audio playback position changed). There currently isn't a way to prevent the default behaviour. Can I ask what the use case is for preventing seeking when clicking on segments? Would you want to do this for all segments, or only particular ones?

**Comment by Foreweed** [comment]
I want the user to be able to modify the audio. So I make him select the parts he wants to delete, and I want to prevent him from playing those parts. This behavior must occur on every deleted segments (which have a special id format).

**Comment by oncletom** [comment]
@Foreweed maybe you can try to intercept the click and user behaviour outside of peaks to do so.

If we move the scrub/click event emission, at least it would enable the user to possibly do a `preventDefault()` to cancel

```js
peaks.on('segment.click', (event, segment) => {
  if (segment.metadata.protected === true) {
    event.preventDefault();
  }
});
```

The same thinking should happen for scrubbing — that might be more complex to do it right.

Maybe a simpler approach would to visually make the segments "unmodifiable", let the user click on them and have your UI to say they cannot do it because of specific reason, with links to jump to the next editable timestamp.

**Comment by Foreweed** [comment]
Hi oncletom,

Thank you for your answer, but I found another way to bypass my problem:
Using only one segment: a selection segment. You can cut or crop it, and once the action is done, the peaks instance is refreshed with the audio modified accordingly.
Like that, I don't have unplayable segments to deal with.

**Comment by oncletom** [comment]
👍
