### ISSUE TITLE
Simple music player - possible to remove advanced features - zooming and segmenting?

### ISSUE THREAD

**Issue by jurgenwerk** [bbc/peaks.js#193]
I'm building a simple web music player app and since I'm generating waveform data using `audio_waveform-ruby` I thought about using `peaks.js` to display the waveform along with a simple play/pause interface and track progress indicator.

Basically, I'd like to replicate SoundCloud's player:

![image](https://user-images.githubusercontent.com/273660/27253588-d22e6626-5377-11e7-9304-1130f529e31a.png)

Is it possible to use a stripped-down version of peaks.js to implement a simple music player like this? How would you go about it?

And thanks for making peaks.js 🙏 .

**Comment by chrisn** [comment]
Thanks for the kind feedback!

Peaks.js is currently designed to have the two waveform views you see in this [screenshot image](https://raw.githubusercontent.com/bbc/peaks.js/master/peaks.png). There are other projects out there that are closer to what you want, are there particular reasons you prefer Peaks.js?

That said, there is [work underway](https://github.com/bbc/peaks.js/pull/177) to restructure the code to support a single view, but it's slow progress due to the time I have available.

If you want to do it yourself, you could always take the Peaks.js code and strip out all the functionality you don't need. There's code in [this pull request](https://github.com/bbc/peaks.js/pull/181) to implement the highlight (orange) region.

**Comment by chrisn** [comment]
Release 0.10.0 allows you to create a single waveform view. Please see https://github.com/bbc/peaks.js/blob/master/demo/overview-waveform.html folder for an example.
