### ISSUE TITLE
Long duration audio waveform controls not working

### ISSUE THREAD

**Issue by ambhar** [bbc/peaks.js#197]
I am using Web Audio API to convert my Audio to Audio Waveforms using Peaks.js. I have noticed an issue, of which I am not sure if there is any solution in any of threads here. 
For audio waveforms which are long in duration, say 20-30 minutes, the vertical bar on the waveform which moves with the audio is not responding to mouse events. Whenever I try to move it to the desired time location, it resets to start time and start playing audio from the initial point.
Though it works for smaller audio files fine, e.g up to 60 seconds of audio files.
Any pointers?

**Comment by chrisn** [comment]
I just tried to reproduce this with a 30 minute MP3 file. It takes a long time to display the waveform, which is why we recommend using `audiowaveform` to preprocess the audio instead of using the Web Audio API. But, once the waveform is displayed, the playhead (the vertical bar) works fine. Do you have an example I can look at?
