### ISSUE TITLE
Playhead jumps shortly after starting playback

### ISSUE THREAD

**Issue by chrisn** [bbc/peaks.js#205]
Following #199, #202, and #204, one small issue with the playhead marker remains: The playhead marker sometimes jumps backwards shortly after starting playback. This can be seen in zoomable waveform view in the Peaks.js demo page.

cc @jdelStrother if you have any ideas?

**Comment by jdelStrother** [comment]
Confirmed.  Will see what I can do

**Comment by chrisn** [comment]
Thanks! I'll hold off on publishing 0.9.5 while we investigate.

**Comment by jdelStrother** [comment]
Yeah....not entirely sure of the best way of dealing with this.  If you look at the audio node's `currentTime` when the play event is received, and compare it to `currentTime` when subsequent timeupdate events arrive, it's consistently around 60ms behind the elapsed wall clock time, which I think is what's causing the jump.  Chrome sends timeupdate events every 250ms, so I _think_ that 250ms after you press play, the playhead jumps backwards 60ms.

I've experimented with a couple of options...

* don't start the play animation when the play event is received - instead, start it on timeupdate.   It looks less broken because the playhead doesn't animate forwards then jump backwards - it just jumps forwards - but it does feel pretty laggy.

* Ditch the playhead's `Konva.Animation` entirely.   Instead, during playback, continually fire requestAnimationFrame, read audio.currentTime, and update the playhead's position from that.  I think this is the most promising - there is a tiny jump in the playhead a few milliseconds after playback starts, but it's much less noticeable, and is otherwise pretty smooth.

Any thoughts?

**Comment by chrisn** [comment]
Resolved via #207.
