### ISSUE TITLE
Can we use AudioContext backed by BufferSource?

### ISSUE THREAD

**Issue by mrfortynine** [bbc/peaks.js#240]
The example of using AudioContext assumes that the data comes from a `mediaElement`. But what if I already have audio data in the form of raw PCM in memory?

**Comment by itsIncept** [comment]
From my knowledge, peaks only uses a mediaElement, so you have to convert PCM to something a <audio> tag can use (I believe there are libraries for that). A quick search revealed [https://github.com/pdeschen/pcm.js/](pcm.js?)

If you're wondering why its because the Web Audio API is weird and doesn't allow you to pause buffer sources so control becomes more of a hacky thing. Wavesurfer does the hacky way (save time, kill, reinitialise at time) so you could try look into that, but there is no officially documented way as they were initially designed to be one-shot less than 30 second kinda items (but you can still fit really long stuff in there so people abuse it haha).

**Comment by chrisn** [comment]
@mrfortynine If you have a Web Audio [`AudioBuffer`](https://developer.mozilla.org/en-US/docs/Web/API/AudioBuffer) then you'll soon be able to pass this to Peaks.js. [This change](https://github.com/bbc/peaks.js/commit/8ada443d98721904cb12cbaf2456479d1db11624) will be in the next release version.

**Comment by dhulme** [comment]
@chrisn Hi, I've used the example from the docs but I think the new version hasn't been published yet? Looking forward to the release! Thanks for all your work :)

**Comment by chrisn** [comment]
@dhulme I have just published v0.13.0, which includes this feature. I'll close this issue as resolved, but please re-open if there are any problems. Thanks!

**Comment by dhulme** [comment]
Thanks for your thoughts. For now I've got it working nicely calling the PlayheadLayer class, with the understanding that this could break in the future!
