### ISSUE TITLE
Questions: using more then one peaks instances with Tone.js players

### ISSUE THREAD

**Issue by noaLeibman** [bbc/peaks.js#386]
I have a few Peaks instances, all with an external player based on Tone.js. Every Peaks instance has it's own external player instance but they are all synced with Tone.Transport so when I call `Tone.Transport.start()` they all start playing together.

1. If I call `player.play()` on one of the Peaks instances, it makes the other ones start as well. Is it because of the 'player.play' event? I guess I'm trying to ask- does it matter which emitter was used to emit that event or is it all the same emitter really?
2. Is there a way to get them to play separately? 
3. What I really don't understand is why when I call *only* `Tone.Transport.start()` it makes the peaks instances play and the cursor and waveform to respond accordingly?

In general it works, but sometimes it's buggy, so I feel like there's a better way to make them play together... I want to understand how it works to implement this correctly:)

**Comment by chrisn** [comment]
> I have a few Peaks instances, all with an external player based on Tone.js. Every Peaks instance has it's own external player instance but they are all synced with Tone.Transport so when I call `Tone.Transport.start()` they all start playing together.

I haven't tried this myself, so I'm not familiar with what's involved, but I'll try to answer where I can.

> 1. If I call `player.play()` on one of the Peaks instances, it makes the other ones start as well. Is it because of the 'player.play' event? I guess I'm trying to ask- does it matter which emitter was used to emit that event or is it all the same emitter really?

Each Peaks instance is its own event emitter. You should find that when you start playback, you get a `player.play` event from each Peaks instance. The event is not used to control other Peaks instances (or your Tone.js based player).

Playback is controlled from the `player` object that you pass to `Peaks.init()`. You can see this [here](https://github.com/bbc/peaks.js/blob/952b84e49d9cf7bb1ba5059f7a690a342cec18e9/demo/external-player.html#L181) in our example demo page.

> 2. Is there a way to get them to play separately?

If all your Peaks instances are connected to the same transport, then I assume playing one will play them all. To play them separately, I guess that would you need separate transports.

> 3. What I really don't understand is why when I call _only_ `Tone.Transport.start()` it makes the peaks instances play and the cursor and waveform to respond accordingly?

The Peaks playhead position updates because the `player` object polls the `Tone.Transport` to get the current playback time (see [here](https://github.com/bbc/peaks.js/blob/952b84e49d9cf7bb1ba5059f7a690a342cec18e9/demo/external-player.html#L165).

> In general it works, but sometimes it's buggy, so I feel like there's a better way to make them play together... I want to understand how it works to implement this correctly:)

I'm not sure what you're trying to do, or what seems buggy. Do you want to view multiple waveforms and sometimes play them back at the same time and sometimes play them individually?

**Comment by noaLeibman** [comment]
Thanks @chrisn for your answer.

In my implementation, I removed the part where the external player polls `Tone.Transport`, since It caused all the players to stop when the one with the shortest buffer reached its end. And anyway it's meant to stop Tone.Transport when the audio finished playing, not to start Peaks when Tone.Transport started, right?

So I still don't understand- how does Peaks know when I call `Tone.Transport.start()` without emitting any events?

What I'm doing in general is working on a web music editor- So I'm using Tone to record and play (and also for synthesizers), and Peaks to display the playing of the recorded audio tracks. The editor can have a few tracks at the same time, each one with a different Peaks instance.

Most of the time when I call `Tone.Transport.start()`, all of the Peaks instances start together (sound + display), but sometimes one of them doesn't, or starts only after I click its waveform. so that's why I mean when I say it's buggy :)

**Comment by chrisn** [comment]
If I comment out the `Tone.Transport.scheduleRepeat()` call from the demo page to disable polling, and change the Play button to call `Tone.Transport.start()` instead of `peaksInstance.player.play()`, I can see that the Peaks waveform doesn't update during playback. This is what I'd expect. There is no event from Tone.js that tells Peaks when it starts, so (with the demo page) the only way that Peaks updates is because it's polling the transport. I'm not sure I can help more without seeing the code you've written.

**Comment by noaLeibman** [comment]
I still don't know why it works for me- but it wasn't perfect (sometimes not all peaks instances would start together),
so I changed the external player to **not** call `Tone.Transport.start()` in the `play` function, and scheduled a call to `this.play()` on `Tone.Transport` at time 0.

This way all the Peaks instances always start together.

```
class Player {
  externalPlayer: Tone.Player;
  eventEmitter: any;

  constructor() {
    this.externalPlayer = new Tone.Player().toDestination();
  }

  init(eventEmitter: any) {
    this.eventEmitter = eventEmitter;
    this.externalPlayer.sync().start(0);

    eventEmitter.emit('player.canplay');
    console.log(eventEmitter);
    Tone.Transport.schedule(() => {
      this.play();
    }, 0);
  }

  play() {
    this.eventEmitter.emit('player.play', this.getCurrentTime());
    return new Promise<void>((resolve) => {});
  }
 ...
};
```
Maybe this will help someone.. Thanks for all your help!

**Comment by chrisn** [comment]
You're welcome. Thank you for posting your solution. Can I close this issue?
