### ISSUE TITLE
Delay on zoom functions on a Vue.js app

### ISSUE THREAD

**Issue by candeogi** [bbc/peaks.js#406]
I noticed some delay in the zoom functions by implementing peaks.js in a vue.js application.
The audio file used in the video below is relatively short so the delay is only a few seconds but I've tried using longer audio files and the delay becomes quite significant (5+ seconds using a 8min audio file). 

I'm not sure if this is a bug or i'm implementing it wrong. 

Link to the [repository ](https://github.com/candeogi/peaks-vue-demo) and the [page](https://candeogi.github.io/peaks-vue-demo/) used in the video.

https://user-images.githubusercontent.com/10027781/124955122-18ceae80-e017-11eb-9fda-f45fd3f2d176.mp4

**Comment by chrisn** [comment]
Changing zoom level involves doing some computation on the waveform, and the more waveform data you have the longer it takes. Some thoughts on what we could do:
* Add a cache of waveform data at different zoom levels. This would reduce the time to switch between zoom levels, although it would still be slow the first time you switch to each zoom level.
* Pre-populate the waveform data for different zoom levels. If we use a worker, this could be done in the background, so the waveform data would be more likely to be ready when you switch the zoom level.

**Comment by candeogi** [comment]
Hi Chris, the problem I encountered seems to be specific to Vue.js (or my implementation using it), normally i've never encountered this kind of delay. There seemed to be some memory management issue in my implementation that was causing the zoom lag.

I've looked into it this morning and solved it with this workaround.
https://github.com/candeogi/peaks-vue-demo/commit/d4e956e4bdb51f7fea9fe0610c485fb7ab7aced0

**Comment by suterma** [comment]
I can very much confirm this exact issue, and the solution seems to work. However, the cause of the problem is unclear to me.

**Comment by chrisn** [comment]
Is this an issue in Peaks.js or in Vue? I'd be interested to see a performance timeline that shows where the delay is coming from.

**Comment by suterma** [comment]
Yes, I believe this is Vue-specific, and related to reactivity. I am not very experienced with the performance tools, but this is what I got when clicking on my zoom button:

![Screenshot from 2022-08-24 17-25-02](https://user-images.githubusercontent.com/11473920/186458940-d540beab-dba4-4d16-b10c-2e3127c5af6c.png)

Code is from my upcoming Vue-wrapper, which currently is more or less what @candeogi was using BEFORE his workaround. I can not see counts of individual method calls, but at the bottom, in the pale blue area there are thousands of short calls to methods that seem to have a relation to reactivity.

**I guess the trick would be to remove the reactivity in the part when registering or executing the button event handlers.**

**Comment by suterma** [comment]
I can now confirm that (deep) reactivity was the culprit. I am working with vue3 refs, and replacing them with shallow refs solved the problem.

So instead of 

`const peakInstance = ref<Peaks.PeaksInstance | undefined>(undefined)`

I do 

`const peakInstance = shallowRef<Peaks.PeaksInstance | undefined>(undefined)`

The problems with the slow handlers got away immediately.

See https://github.com/suterma/vue-peaks/blob/a064e2c5cf53c918efcf625c000659853dbb4025/src/components/AudioPeaks.vue#L10 if you are interested in the actual code. It's work in progress, but the goal is to have a (thin) vue wrapper around peaks.js.

**Comment by suterma** [comment]
What I can additionally say, is that the problem is worse when the zoom level is smaller (smaller value) and the file is larger. This aspect of the problem is most probably coming from peaks.js itself, but I guess this is an inherent property of the buffer-oriented internal workings of peaks.js, not an implementation issue per se.

**Comment by chrisn** [comment]
Thanks, I'm not at all familiar with Vue, so I learned something. Changing zoom level involves some computation, but by default the results are cached for each zoom level, so it's only slow the first time you change to a previously-unused zoom level.

**Comment by suterma** [comment]
Yes, @chrisn I also made this observation about first-time use taking longer. All in all, this issue can be kept closed, as the specific problem that was initially reported by @candeogi actually is Vue-related and not caused by peaks.js.

Also, a solution has been proposed by @candeogi themselves and @suterma (me) could verify and pin the issue. Thanks, guys, for all your work with this great library.
