### ISSUE TITLE
Allow dragging an entire segment

### ISSUE THREAD

**Issue by Lornz-** [bbc/peaks.js#443]
Hi! I'm currently working on a project using **peaks.js** and I was wondering if the following functionality from another library ([wavesurfer.js](https://wavesurfer-js.org/plugins/regions.html)) is something we can do by customization in some way? Otherwise is that something you plan to add to the api in a future release?

https://user-images.githubusercontent.com/901831/156260731-0c67ec52-5ebf-47aa-b5f3-caf72dca4ab2.mp4

**Comment by chrisn** [comment]
Thank you for suggesting this. I think implementing this would require changes to the library, rather than being possible through the current API and customisation options. I'd be open to adding this, although no current plans.

The default drag operation is to scroll the waveform so I'd want to make this optional in some way.

**Comment by Lornz-** [comment]
Thanks @chrisn for answering me back. In what time window do you think it could be added? I just wanna know if I could wait for some times before to be able to use it or do I have to find an alternative if I have to wait longer? Being said, are you opened to get a monetary contribution in order to work on that feature in priority?

**Comment by chrisn** [comment]
This is now available for testing in version 3.0.0-beta.0. Please see [doc/migration-guide.md](doc/migration-guide.md) as there some breaking API changes.

```
npm install peaks.js@beta
```
