### ISSUE TITLE
point.update doesn't redraw the point

### ISSUE THREAD

**Issue by evfinkn** [bbc/peaks.js#498]
Updating a point's `color`, `labelText`, and `editable` attributes using `point.update` doesn't redraw the point on the zoomview nor overview. If you seek to a different time and then back to the point, the point will be updated on the zoomview, but the overview remains unchanged. Note that updating the point's time works correctly, as does updating a segment.

**Comment by chrisn** [comment]
Thanks for reporting this, I'll investigate. Which Peaks,js version are you using?

**Comment by evfinkn** [comment]
Sorry, I should've specified. I'm experiencing this on [the latest commit to master](https://github.com/bbc/peaks.js/commit/53d3e6491418f7c9943729cabc220ded5aa2fd47). Not sure what version it stopped working in since I updated to latest from version 2.1.0.

**Comment by chrisn** [comment]
This is really helpful feedback, thanks.

I'll need to rethink this change. In 2.1.0, updates cause the point/segment to be deleted and re-created, which was simple to implement and meant that updates would always work.

In the 3.0.0-beta development I changed this so that points/segments don't get deleted but instead have an internal `update()` method that gets called when attributes are changed. The new way is more complex and not fully implemented yet.

**Comment by chrisn** [comment]
This should be fixed in v3.0.0-beta.12. The custom marker `update()` methods are now called correctly. If you're using custom markers, the [migration guide](https://github.com/bbc/peaks.js/blob/master/doc/migration-guide.md) explains how to update your code.

One limitation is that changing `editable` is not currently implemented, but I'm not sure how important that is.

**Comment by evfinkn** [comment]
Thanks for the fix. I update `editable` so that the drag markers can be hidden and shown, but it's not a big deal if it's not a priority fix 👍

**Comment by chrisn** [comment]
Thanks, I'll see what I can do...

**Comment by chrisn** [comment]
Changing segment `editable` should now be working in v3.0.0-beta.13.

**Comment by evfinkn** [comment]
Works great. Thanks!
