### ISSUE TITLE
Problem to re play a streaming audio

### ISSUE THREAD

**Issue by CaleoSystems** [bbc/peaks.js#515]
### Discussed in https://github.com/bbc/peaks.js/discussions/514

<div type='discussions-op-text'>

<sup>Originally posted by **CaleoSystems** November 28, 2023</sup>
Hello,
I am using Peaks to play audios stored on a remote server served by a NodeJS based streaming server. Everything works fine before the audio ends, when the audio ends and I play it again I can't go forward or back since it always sends it to the beginning. This behavior only occurs with streaming and not with local audio.

Thanks for your help.</div>

**Comment by chrisn** [comment]
Which streaming server / library are you using?

Related: https://github.com/bbc/peaks.js/issues/189

**Comment by chrisn** [comment]
Thanks. Seeking probably isn't working because the browser isn't caching all the audio, and it can only seek within time regions it has cached. For that to work, you can serve the audio as a static file, so the browser can request the time regions it wants to play (see https://github.com/bbc/peaks.js/blob/master/doc/faq.md).

**Comment by CaleoSystems** [comment]
Chris, I really appreciate your help.

This problem is not happening on Firefox, I will try some fix according to the reference you mentioned.

Thank you very much.

**Comment by chrisn** [comment]
I'll close this, but if it still isn't working please re-open the issue.
