### ISSUE TITLE
setZoom auto has little error

### ISSUE THREAD

**Issue by jason30704** [bbc/peaks.js#536]
Hello,
I use the following code to set zoom to auto.
But it does not completely cover the entire waveform.
As the video shows, it can still slide. Is there a way to ensure that it is fully covered?

https://github.com/user-attachments/assets/f648353c-aa55-424b-990a-3dcd84e4ae8b

```
const WaveformView = ({ audioCtx, audioElementRef}) => {
  const [peaks, setPeaks] = useState(null);
  const zoomviewWaveformRef = useRef(null);
  const overviewWaveformRef = useRef(null);

  useEffect(() => {
    initPeaks();
  }, []);

  const initPeaks = () => {
    const options = {
      overview: {
        container: overviewWaveformRef.current,
        axisGridlineColor: "transparent",
        showAxisLabels: false,
      },
      zoomview: {
        container: zoomviewWaveformRef.current,
        axisGridlineColor: "transparent",
        showAxisLabels: false,
      },
      mediaElement: audioElementRef,
      keyboard: true,
      logger: console.error.bind(console),
      zoomLevels: [512, 2048, 4096, 10000],

      webAudio: {
        audioContext: audioCtx,
      },
    };

    if (peaks) {
      peaks.destroy();
      setPeaks(null);
    }

    Peaks.init(options, (err, peaks) => {
      setPeaks(peaks);
      if (err) {
        console.log(err);
        return;
      }

      peaks.views.getView("overview").enableMarkerEditing(true);
      peaks.views.getView("zoomview").setZoom({ seconds: "auto" });
      peaks.views.getView("zoomview").setSegmentDragMode("compress");

      // onPeaksReady();
    });
  };

  return (
    <Box width={"600px"}>
      <Box className="zoomview-container" ref={zoomviewWaveformRef}></Box>
      <Box className="overview-container" ref={overviewWaveformRef}></Box>
    </Box>
  );
};
```

**Comment by jason30704** [comment]
Also, is it not possible to prevent zoomview drag now?
Using the following two functions will cause an error.
```
peaks.views.getView("zoomview").enableDragScroll(false);
peaks.views.getView("zoomview").enableAutoScroll(false);
```
![image](https://github.com/user-attachments/assets/b67f7b74-33a3-4749-b167-9045a38e820f)

**Comment by chrisn** [comment]
I have fixed the bug in `enableAutoScroll()` in https://github.com/bbc/peaks.js/commit/e7f049c6391bbe2be1ee1a27a2c42714cc22dda3.

There is no `enableDragScroll()` function, try using [`setWaveformDragMode()`](https://github.com/bbc/peaks.js/blob/master/doc/API.md#viewsetwaveformdragmodemode).

**Comment by chrisn** [comment]
The zoom 'auto' problem is fixed in https://github.com/bbc/peaks.js/commit/b6e166251c674c9436be8432d1ceafaba003fcbf.

**Comment by chrisn** [comment]
I have published v3.4.1 to npm, with both these fixes.

**Comment by jason30704** [comment]
Thanks for your response and quick fix
However, the modification in 3.4.1 is "Prevent scrolling the zoomview when set to auto zoom". But if you zoomview during playback, it will still be affected by autoScroll and you can slide. (Of course, we can also cancel autoScroll)
In addition, when sliding the overview, there will still be the same problem.
I think the root cause may be that in some cases the overview and zoomview will have different widths.

The following are the results of my own use. Among the three audios, only the third audio does not have misalignment problems.
Not sure if it’s related to the length of the video?
https://github.com/user-attachments/assets/0b0ef9ae-a5f9-4655-95fc-023527ca7d1c

**Comment by chrisn** [comment]
I can reproduce the problem here, so there's no need to upload your files. But thank you for offering, it's really helpful.

There are two problems I can see:
* The waveform length is different in the zoomview and overview when you set auto zoom (they should be the same)
* The waveform resampling doesn't guarantee you get the requested number of pixels. For example, resizing the waveform to fit a 1000 pixel width might give you 1002 samples, and this is what causes the movement when playback reaches the end of the audio.

Fixing the first one is easy, the second is a bit more involved. For now, I can prevent the auto-scroll when you set auto zoom, but to fix this properly means changing the waveform resampling to support floating-point `scale` (samples per pixel) values. Currently these are integer, which causes a rounding error, which leads to the resampled waveform length being close to but not exactly the length requested. This would need changing in both [audiowaveform](https://github.com/bbc/audiowaveform) and [waveform-data.js](https://github.com/bbc/waveform-data.js)

**Comment by chrisn** [comment]
Please try v3.4.2, which prevents the waveform from scroll when the zoom is set to 'auto'.

**Comment by jason30704** [comment]
I understand, thanks for the explanation.
After using version 3.4.2, I feel that it is much better to use! It seems that this is already a good workaround for now.
Thank you so much.

**Comment by chrisn** [comment]
Thank you too, for raising these issues. It all helps improve this package.
